services:
  streamlit-app:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge