services:
  streamlit-app:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    networks:
      - app-network
    restart: unless-stopped

  rag-backend:
    build:
      context: ./AI
    ports:
      - "5000:5000"
    volumes:
      - ./AI:/app
      - ./shared_data:/app/shared_data
    networks:
      - app-network
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  scraper:
    build:
      context: ./scraper
    volumes:
      - ./scraper:/app
      - ./shared_data:/shared  # Lokalny katalog - łatwiejszy dostęp
    networks:
      - app-network
    restart: "no"
    environment:
      - PYTHONUNBUFFERED=1
      - SCRAPER_URL=https://www.biedronka.pl/pl/oferta-z-karta-moja-biedronka
      - MAX_PRODUCTS=50
      - OUTPUT_FILE=/shared/biedronka_offers.json
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: ["sh", "-c", "python -u main.py && python -u enhancer.py && python -u filter.py"]


networks:
  app-network:
    driver: bridge
