apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: olszewskib/teg-frontend:v3
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: frontend-config
          volumeMounts:
            - name: food-images
              mountPath: /app/Images
      volumes:
        - name: food-images
          persistentVolumeClaim:
            claimName: food-images
